Added variables to control component deployment
terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent pull request #113
Opened 2024-05-06 10:11 UTC by ctolon22

### Description

Added variables to control the deployment of scc workload protection components.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [X] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-06 10:12 UTC, ctolon22 commented
/run pipeline

2024-05-07 08:58 UTC, ocofaigh requested changes
Hey Carlos, thanks for the PR - I think you need to set up your local dev environment so you can run the pre-commit hooks on your code. If I try to trigger the pipeline now it will fail due to the missing content that is automatically fixed / added by those hooks (such as linting, formatting and documentation).
Its really easy to set it up though, just follow the few steps here -> https://terraform-ibm-modules.github.io/documentation/#/local-dev-setup

I also left a few comments

2024-05-07 08:58 UTC, ocofaigh commented on variables.tf
> +  default     = "terraform"
Does it support multiple tags (so should this be a list?). 
Also what exactly is the tag used for? I think consumers need more information in order to understand what the value should be set to

2024-05-07 08:58 UTC, ocofaigh commented on variables.tf
> +  description = "Deploy SCC Workload Protection host scanner component. If node_analyzer_deploy false, this component will not be deployed."
you have `node_analyzer_deploy` and `host_scanner_deploy` both set to `true`, however your saying this can't be the case right? so should one of them default to false? And should we add conditional logic to the main.tf to ensure this?

2024-05-07 09:16 UTC, ctolon22 commented on variables.tf
> +  default     = "terraform"
This is a tag to be included in the workload protection components. 
It represents the mechanism from where it has been installed (terraform, local...) so customers can add that.
It's just one tag

2024-05-07 09:18 UTC, ctolon22 commented on variables.tf
> +  description = "Deploy SCC Workload Protection host scanner component. If node_analyzer_deploy false, this component will not be deployed."
Host scanner runs inside node-analyzer. You can run the node analyzer with or without the host scanner. It's a different use case so that's why i added the variable

`host_scanner_deploy` is ignored if `node_analyzer_deploy` is false. We can add conditional logic but won't change much the behavior

2024-05-09 13:30 UTC, ocofaigh commented on variables.tf
> +  default     = "terraform"
ok, but can we include that information in the variable description so its clear to consumers where it is used?

2024-05-09 13:30 UTC, ocofaigh commented on variables.tf
> +  description = "Deploy SCC Workload Protection host scanner component. If node_analyzer_deploy false, this component will not be deployed."
ok, I guess its fine to leave then

2024-05-09 14:12 UTC, ocofaigh commented
/run pipeline

2024-05-09 16:10 UTC, ocofaigh approved these changes

2024-05-09 16:11 UTC, merged

2024-05-09 16:11 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: