feat: add SCC WP agent  module implementation
terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent pull request #15
Opened 2023-12-08 14:27 UTC by akocbek

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-12-08 14:27 UTC, akocbek commented
/run pipeline

2023-12-08 16:13 UTC, ocofaigh requested changes
I left an initial round of comments. Lets regroup next week to discuss more, because this is the first use case where we have a helm chart that calls multiple images. I see we are locking into chart version "1.30.0" - does every chart release have a set of hard coded image versions in it? Because with the approach we have in the code now, using renovate we will end up deploying images version that did not come with the chart. Personally I think we need to be pulling the chart, checking the versions of all images in the chart, mirroring them to our ICR namespace, and adding the image SHAs in the code for each of the images. I don’t know off the top of my head any other way to achieve this but by writing custom automation. Perhaps for the initial release we disable renovate updates and lock into the images we know come with “1.30.0” ?

2023-12-12 15:17 UTC, akocbek commented on variables.tf
> +  default     = null
fix

2023-12-12 15:17 UTC, akocbek commented on variables.tf
> +}
fix

2023-12-12 15:17 UTC, akocbek commented on variables.tf
> +  description = "Workload Protection instance ingestion endpoint."
added some info and validation. Should we mention that terraform-ibm-modules/terraform-ibm-scc-workload-protection return endpoints output variable?

2023-12-12 15:18 UTC, akocbek commented on variables.tf
> +}
fixed

2023-12-12 15:19 UTC, akocbek commented on variables.tf
> +  default     = "ibm-observe"
used `ibm-scc-wp` let me know if you have better suggestion

2023-12-12 15:30 UTC, akocbek commented
/run pipeline

2023-12-12 15:30 UTC, akocbek commented on examples/basic/version.tf
> +      version = "1.59.0"
we will add additional test later, now range is used

2023-12-12 15:31 UTC, akocbek commented
/run pipeline

2023-12-12 15:32 UTC, akocbek commented on README.md
> +- SCC WPA can not be used inside private VPC, because it uses `public` and `private` endpoints only, while private VPC uses `direct` endpoint. Therefore, to use SCC WPA with VPC, the public gateway m
done

2023-12-12 15:32 UTC, akocbek commented
/run pipeline

2023-12-12 15:39 UTC, akocbek commented
/run pipeline

2023-12-12 16:16 UTC, akocbek commented
/run pipeline

2023-12-12 16:22 UTC, ocofaigh requested changes
see comments

2023-12-12 16:22 UTC, ocofaigh commented on README.md
>  ### Required IAM access policies
You need to fill in this section. As this is just a helm chart deployment in a kube cluster, I presume all you need is:
```
- IAM Services
  - **Kubernetes** service
      - `Viewer` platform access
      - `Manager` service access
```

2023-12-12 16:22 UTC, ocofaigh commented on examples/basic/provider.tf
> +# Helm provider used to deploy cluster-proxy and observability agents
comment is not valid for this example

2023-12-12 16:22 UTC, ocofaigh commented on examples/basic/provider.tf
> +# Kubernetes provider used to create kube namespace(s)
comment is not valid for this example

2023-12-12 16:22 UTC, ocofaigh commented on examples/basic/variables.tf
> +  default     = "base-scc-wp-andrej"
remove `andrej` from here

2023-12-12 16:22 UTC, ocofaigh commented on examples/basic/variables.tf
> +  description = "The IBM Cloud api token"
can you change this back, its an api key, not a token

2023-12-12 16:22 UTC, ocofaigh commented on examples/basic/variables.tf
> +variable "access_tags" {
No need to add access tag for this basic example. Access tags are not applicable for the agent anyway, just instance

2023-12-12 16:22 UTC, ocofaigh commented on outputs.tf
> +  sensitive   = true
ID? I dont think there is such a thing with the `helm_release` resource: https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release

2023-12-12 16:22 UTC, ocofaigh commented on outputs.tf
> +  description = "Name of provisioned SCC WP agent."
You better say this is the helm chart release name

2023-12-12 16:22 UTC, ocofaigh commented on outputs.tf
> +  sensitive   = true
this is not sensitive?

2023-12-12 16:22 UTC, ocofaigh commented on variables.tf
> +}
I just came across this doc which shows all supported endpoints -> https://cloud.ibm.com/docs/workload-protection?topic=workload-protection-endpoints

It seems we can always programmatically determine both the api endpoint and the ingestion endpoint, so I think I have changed my mind and lets just have 1 variable saying `endpoint_type` with allowed values of `public` or `private`. Then in the module logic we can construct the api and ingestion endpoints to use in the helm install.

2023-12-12 16:22 UTC, ocofaigh commented on examples/basic/outputs.tf
> +  description = "ID of provisioned SCC WP agent."
As per the comment in outputs.tf there is no ID here to output, so remove this

2023-12-12 16:22 UTC, ocofaigh commented on examples/basic/outputs.tf
> +  description = "Name of provisioned SCC WP agent."
This is helm release name

2023-12-12 16:22 UTC, ocofaigh commented on examples/basic/outputs.tf
> +  sensitive   = true
this is not sensitive

2023-12-13 11:40 UTC, akocbek commented on examples/basic/outputs.tf
> +  sensitive   = true
fixed

2023-12-13 11:40 UTC, akocbek commented on examples/basic/outputs.tf
> +  description = "Name of provisioned SCC WP agent."
fixed

2023-12-13 11:40 UTC, akocbek commented on examples/basic/outputs.tf
> +  description = "ID of provisioned SCC WP agent."
removed

2023-12-13 11:40 UTC, akocbek commented on outputs.tf
> +  sensitive   = true
fixed

2023-12-13 11:40 UTC, akocbek commented on examples/basic/variables.tf
> +  description = "The IBM Cloud api token"
fixed

2023-12-13 11:40 UTC, akocbek commented on examples/basic/variables.tf
> +  default     = "base-scc-wp-andrej"
fixed

2023-12-13 11:40 UTC, akocbek commented on examples/basic/provider.tf
> +# Kubernetes provider used to create kube namespace(s)
fixed

2023-12-13 11:40 UTC, akocbek commented on examples/basic/provider.tf
> +# Helm provider used to deploy cluster-proxy and observability agents
fixed

2023-12-13 11:40 UTC, akocbek commented on README.md
>  ### Required IAM access policies
added

2023-12-13 11:41 UTC, akocbek commented on outputs.tf
> +  sensitive   = true
fixed

2023-12-13 11:41 UTC, akocbek commented on outputs.tf
> +  description = "Name of provisioned SCC WP agent."
fixed

2023-12-13 11:42 UTC, akocbek commented on examples/basic/variables.tf
> +variable "access_tags" {
removed

2023-12-13 11:43 UTC, akocbek commented
/run pipeline

2023-12-13 12:52 UTC, akocbek commented
/run pipeline

2023-12-13 17:03 UTC, ocofaigh requested changes
final small comments

2023-12-13 17:03 UTC, ocofaigh commented on examples/basic/provider.tf
> +  # for this example, we will disable public endpoints and specify to use "private" endpoint for cluster
in this example you have not disabled public endpoints in the cluster, so the comment doesn't make sense here. All this does is connect to the cluster over the private endpoint instead of public. 
What I am confused about here is how can our pipeline connect to the cluster over the private endpoint when it doesn't run inside the IBM network (its running on public github)?

2023-12-14 12:03 UTC, akocbek commented
/run pipeline

2023-12-14 13:49 UTC, ocofaigh approved these changes

2023-12-14 13:50 UTC, merged

2023-12-14 13:52 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: