Feat: Add admission controller
terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent pull request #189
Opened 2024-10-15 17:43 UTC by ctolon22

### Description

Add support for installing SCC-WP Admission Controller:
- Webhook
- KSPM admission controller

It's disabled by default

It requires adding Sysdig API Token when used.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-10-15 17:58 UTC, ocofaigh requested changes
Left some comments - is there a reason why we would not enable the admission controller by default?

2024-10-15 17:58 UTC, ocofaigh commented on variables.tf
> +  default     = ""
use a default value of `null` instead of an empty string

2024-10-15 17:58 UTC, ocofaigh commented on variables.tf
> +    condition     = var.admission_controller_enabled == true && var.admission_controller_token != ""
cross variable validation only came in terraform 1.9, so if we want to use it, we need to bump the required terraform version of the module to `>= 1.9.0`, however Schematics agents do not yet support terraform 1.9 so we are waiting for that support before requiring this version in any of our modules / DAs.

Until then, you can use a workaround using locals like so: https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/c2f8765c27c27f39cc87e5610037d1b32fa8bd1a/main.tf#L18-L19

I'm following up with the Schematics team on the support for agents

2024-10-17 16:00 UTC, ocofaigh commented on variables.tf
> +  description = "Enables Kubernetes audit logging detections with Falco rules via Admission Controller."
I suggest to mention a value for `admission_controller_token` is required if setting to true

2024-10-17 16:00 UTC, ocofaigh commented on variables.tf
> +  description = "Enables Kubernetes Security Posture Management admission controller for scanning new deployed resources for Posture validation."
I suggest to mention a value for `admission_controller_token` is required if setting to true

2024-10-17 16:00 UTC, ocofaigh commented on variables.tf
> +  default     = null
is token the right terminology? Or is it apikey?

2024-10-17 16:01 UTC, ocofaigh commented on main.tf
> +  validate_admission_controller_inputs = var.admission_controller_enabled && var.admission_controller_token == null ? tobool("var.admission_controller_token is mandatory when enabling Admission Contr
should this validation also check when `admission_controller_kspm_enabled` is true?

2024-10-18 13:47 UTC, ctolon22 commented on variables.tf
> +  default     = null
adding sensitive. It's API Token the terminology (it's different to the access key or an IBM API key)

2024-10-18 14:10 UTC, ctolon22 commented on main.tf
> +  validate_admission_controller_inputs = var.admission_controller_enabled && var.admission_controller_token == null ? tobool("var.admission_controller_token is mandatory when enabling Admission Contr
actually, kspm is one feature of the entire admission controller. So adding a comment that if setting this as true, admission_controller_enabled needs to be true.
That should be enough

2024-10-18 14:45 UTC, ocofaigh commented
/run pipeline

2024-10-18 17:41 UTC, ocofaigh commented
@ctolon22 Test failed with this:
```
│ Error: Missing required argument
│ 
│   with module.scc_wp_agent.helm_release.scc_wp_agent,
│   on ../../main.tf line 36, in resource "helm_release" "scc_wp_agent":
│   36: resource "helm_release" "scc_wp_agent" {
│ 
│ The argument "set.40.value" is required, but no definition was found.
╵}
```

2024-10-18 17:42 UTC, ocofaigh commented
@ctolon22 we probably also want to update the example that the test runs to actually deploy the admission controller so that we test it in PRs

2025-03-10 11:17 UTC, ocofaigh commented
@ctolon22 Are we still planning to implement this?

2025-07-18 18:52 UTC, closed without merging