feat: move agents to new tile
terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent pull request #217
Opened 2024-12-06 15:19 UTC by jor2

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-12-06 15:34 UTC, ocofaigh requested changes
See comments. Can you also:
- add a `.catalog-onboard-pipeline.yaml` (Ill share the offering Id after next commit to this PR)
- update .releaserc to trigger the catalog pipeline

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +        "name": "deploy-arch-ibm-scc-workload-protection-agent",
maybe go with `deploy-arch-ibm-scc-wp-agent`

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +        "label": "Cloud automation for Security and Compliance Center Agents",
It is a bit long, but I think the correct working would be:
"Cloud automation for Security and Compliance Center Workload Protection agent"

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +        "short_description": "Creates and configures IBM Security and Compliance Center resources",
Configures Security and Compliance Center Workload Protection agents

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +        "long_description": "This architecture supports creating and configuring IBM Security and Compliance Center resources.",
This architecture supports creating and configuring IBM Security and Compliance Center Workload Protection agent to an IBM Cloud Kubernentes or Openshift cluster

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +        "offering_docs_url": "https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/blob/main/solutions/instances/README.md",
needs to change to new location

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +        "offering_icon_url": "https://raw.githubusercontent.com/terraform-ibm-modules/terraform-ibm-scc-da/main/images/scc-icon.svg",
suggest to move the icon too

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +            "name": "agents",
We no longer need to call it agents. Suggest to go with:

"label": "Standard",
"name": "standard",

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +            "install_type": "extension",
change this to "fullstack" and add 
`"dependency_version_2": true,`

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +            "working_directory": "solutions/agents",
I guess move the code to a `standard` directory to match the new proposed variation name

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +                ]
these permissions are not needed for agents

2024-12-06 15:34 UTC, ocofaigh commented on ibm_catalog.json
> +                    "url": "https://raw.githubusercontent.com/terraform-ibm-modules/terraform-ibm-scc-da/main/reference-architecture/scc-wp-agent.svg",
update diagram link to this repo

2024-12-06 15:54 UTC, jor2 commented
> See comments. Can you also:
> 
> * add a `.catalog-onboard-pipeline.yaml` (Ill share the offering Id after next commit to this PR)
> * update .releaserc to trigger the catalog pipeline

updated and added missing scripts

2024-12-06 16:20 UTC, ocofaigh commented on .catalog-onboard-pipeline.yaml
> +    offering_id: 9423f9bc-1290-4c71-a9ac-01898bfa7ccc
@jor2 change this to `f76f2ed3-eb98-4e3d-b147-360485fd8a36`

2024-12-06 16:24 UTC, jor2 commented
/run pipeline

2024-12-06 16:33 UTC, ocofaigh submitted a review, later dismissed

2024-12-06 18:22 UTC, ocofaigh commented on tests/pr_test.go
> +const agentsKubeconfigDir = "solutions/agents/kubeconfig"
this need to be updated to /solutions/standard. I think thats why the test failed

2024-12-06 19:28 UTC, jor2 commented on tests/pr_test.go
> +const agentsKubeconfigDir = "solutions/agents/kubeconfig"
oh :(

2024-12-06 19:28 UTC, jor2 commented
/run pipeline

2024-12-06 19:31 UTC, jor2 commented
/run pipeline

2024-12-06 19:34 UTC, jor2 commented
/run pipeline

2024-12-09 08:57 UTC, ocofaigh commented
@jor2 you need to resolve conflicts before pipeline can be triggered

2024-12-09 13:27 UTC, jor2 commented
/run pipeline

2024-12-09 14:39 UTC, jor2 commented
/run pipeline

2024-12-09 16:29 UTC, ocofaigh approved these changes

2024-12-09 16:29 UTC, merged

2024-12-09 16:30 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-scc-workload-protection-agent/releases/tag/v1.4.0)
- `v1.4.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: